export const SET_CASE_STUDY_DATA = 'SET_CASE_STUDY_DATA';
export const SET_CASE_STUDY_LOADED = 'SET_CASE_STUDY_LOADED';
export const SET_SERVICE_DATA = 'SET_SERVICE_DATA';
export const SET_CAREER_DATA = 'SET_CAREER_DATA';
export const SET_CAREER_LOADED = 'SET_CAREER_LOADED';
